CHECKLIST_SECTIONS = [
    {
        "key": "seguridad",
        "title": "Elementos de Seguridad (EPP y Entorno)",
        "weight": 30,
        "items": [
            {"key": "casco", "label": "Uso de casco de seguridad", "critical": True},
            {"key": "guantes", "label": "Uso de guantes adecuados", "critical": True},
            {"key": "lentes", "label": "Uso de lentes de proteccion", "critical": False},
            {"key": "chaleco", "label": "Uso de chaleco reflectante", "critical": True},
            {"key": "botas", "label": "Uso de botas de seguridad", "critical": True},
            {"key": "senalizacion", "label": "Señalizacion del area de trabajo", "critical": True},
            {"key": "orden_entorno", "label": "Orden y limpieza del entorno", "critical": False},
            {"key": "detector_voltaje", "label": "280300104 - Detector de voltaje", "critical": True},
            {
                "key": "mentonera_libus_15mm_gancho_c",
                "label": "730100004 - Mentonera Libus 15mm c/logo (Gancho C)",
                "critical": True,
            },
            {"key": "cinta_peligro", "label": "Cinta de peligro", "critical": True},
            {"key": "conos", "label": "Conos", "critical": True},
            {"key": "arnes_completo_anticaidas", "label": "Arnés completo anticaídas", "critical": True},
            {"key": "cola_amarre_separada", "label": "Cola de amarre separada", "critical": True},
            {"key": "extintor", "label": "Extintor vigente", "critical": True},
            {"key": "botiquin", "label": "Botiquín disponible", "critical": False},
        ],
    },
    {
        "key": "herramientas",
        "title": "Estado de Herramientas (Kit de Fibra Optica)",
        "weight": 15,
        "items": [
            {"key": "fusionadora", "label": "Fusionadora operativa", "critical": True},
            {"key": "cortadora", "label": "Cortadora de FO (Cleaver)", "critical": True},
            {"key": "peladora", "label": "Peladora de fibra funcional", "critical": False},
            {"key": "peladora_drop_plano", "label": "Peladora de Drop plano", "critical": False},
            {"key": "medidor", "label": "Power Meter", "critical": True},
            {"key": "laser_localizador_fallas", "label": "Laser localizador de fallas FO", "critical": False},
            {
                "key": "funda_laser_localizador_fallas",
                "label": "Funda para laser localizador de fallas FO",
                "critical": False,
            },
            {"key": "lapiz_limpiador_conector_fo", "label": "Lápiz limpiador conector FO", "critical": False},
            {"key": "limpieza", "label": "Alcohol Ispopropilico + Paño", "critical": False},
            {"key": "baterias", "label": "Cargador USB", "critical": False},
            {"key": "orden_kit", "label": "Bolso kit de fibra", "critical": False},
        ],
    },
    {
        "key": "herramientas_mano",
        "title": "Herramientas de mano",
        "weight": 10,
        "items": [
            {
                "key": "mano_alicate_chico_aislado",
                "label": "280300103 - Alicate chico aislado a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300103",
                "evidence_required": False,
            },
            {
                "key": "mano_destornillador_ph_aislado",
                "label": "281300012 - Destornillador PH aislado Ø6x100mm",
                "critical": False,
                "hand_tool": True,
                "material_code": "281300012",
                "evidence_required": False,
            },
            {
                "key": "mano_destornillador_pl_aislado",
                "label": "281300013 - Destornillador PL aislado Ø6.5x150mm",
                "critical": False,
                "hand_tool": True,
                "material_code": "281300013",
                "evidence_required": False,
            },
            {
                "key": "mano_martillo_bolita_500",
                "label": "280700022 - Martillo de 500 grs bolita",
                "critical": False,
                "hand_tool": True,
                "material_code": "280700022",
                "evidence_required": False,
            },
            {
                "key": "mano_pinza_punta_aislada",
                "label": "280300101 - Pinza de punta aislada a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300101",
                "evidence_required": False,
            },
            {
                "key": "mano_pinza_peladora_claus",
                "label": "280300208 - Pinza peladora Claus CFS2",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300208",
                "evidence_required": False,
            },
            {
                "key": "mano_pinza_universal_aislada",
                "label": "280300100 - Pinza universal aislada a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300100",
                "evidence_required": False,
            },
            {
                "key": "cartuchera_herramientas",
                "label": "Cartuchera porta herramientas",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": False,
            },
            {
                "key": "cartuchera_destornilladores_mini",
                "label": "Cartuchera para destornilladores mini",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": False,
            },
        ],
    },
    {
        "key": "vehiculo",
        "title": "Estado del Vehículo",
        "weight": 20,
        "items": [
            {"key": "documentacion", "label": "Cédula de Identificación del Automotor", "critical": True},
            {"key": "seguro_vehicular", "label": "Seguro vehicular vigente", "critical": True},
            {"key": "oblea_gnc", "label": "Oblea de GNC vigente", "critical": True},
            {"key": "rto", "label": "RTO vigente", "critical": True},
            {"key": "neumaticos", "label": "Neumaticos en buen estado", "critical": True},
            {"key": "luces", "label": "Luces operativas", "critical": True},
            {"key": "elementos_emergencia", "label": "Kit Elementos de Emergencia", "critical": True},
            {"key": "carga_segura", "label": "Escalera y herramientas aseguradas", "critical": True},
            {
                "key": "escalera_aluminio_extensible",
                "label": "Escalera de aluminio extensible (11/13 peldaños)",
                "critical": True,
            },
            {
                "key": "escalera_fibra_tijera_doble",
                "label": "Escalera de fibra de vidrio tipo tijera doble",
                "critical": True,
            },
        ],
    },
    {
        "key": "calidad_instalaciones",
        "title": "Control de Calidad de Instalaciones",
        "weight": 15,
        "items": [
            {"key": "nomenclado", "label": "Nomenclado", "critical": False},
            {"key": "rabillado", "label": "Rabillado", "critical": False},
            {"key": "tensado", "label": "Tensado", "critical": False},
            {"key": "reten_a_cadena", "label": "Reten a cadena", "critical": False},
            {"key": "piton_8_retencion", "label": "Pitón del 8 (retención)", "critical": False},
            {"key": "recorrido_fibra_piton_6", "label": "Recorrido de fibra con pitón del 6", "critical": False},
            {
                "key": "recorrido_fibra_presintada_otro_servicio",
                "label": "Recorrido de fibra presintada a otro Servicio",
                "critical": False,
            },
            {"key": "ingreso_caneria", "label": "Ingreso por cañeria", "critical": False},
            {"key": "ingreso_nueva_perforacion", "label": "Ingreso por nueva perforacion", "critical": False},
            {
                "key": "ingreso_perforacion_existente",
                "label": "Ingreso por perforacion existente",
                "critical": False,
            },
            {"key": "tubo_pasapared", "label": "Tubo pasapared", "critical": False},
            {"key": "loop", "label": "Loop", "critical": False},
            {"key": "sellador", "label": "Sellador", "critical": False},
            {"key": "engrampado_por_vertice", "label": "Engrampado por vertice", "critical": False},
            {"key": "sticker_autoadhesivo", "label": "Sticker autoadhesivo", "critical": False},
        ],
    },
]


TOOL_MATCH_RULES = {
    "fusionadora": {
        "label": "Fusionadora",
        "keywords": ["fusionadora", "sumitomo", "fitel", "fsm"],
    },
    "cortadora": {
        "label": "Cortadora de FO (Cleaver)",
        "keywords": ["cortadora", "cleaver", "ct-30", "fc-6", "precision", "precisión"],
    },
    "peladora": {
        "label": "Peladora de fibra",
        "keywords": ["peladora", "stripper", "pelador", "pela fibra"],
    },
    "peladora_drop_plano": {
        "label": "Peladora de Drop plano",
        "keywords": ["280300209", "peladora", "drop", "plano", "flat drop", "peladora drop", "drop plano"],
    },
    "medidor": {
        "label": "Medidor de potencia",
        "keywords": ["medidor", "power meter", "powermeter", "medidor de potencia", "otdr"],
    },
    "laser_localizador_fallas": {
        "label": "Laser localizador de fallas FO",
        "keywords": ["laser", "láser", "localizador", "falla", "fallas", "vfl", "visual fault locator"],
    },
    "funda_laser_localizador_fallas": {
        "label": "Funda para laser localizador de fallas FO",
        "keywords": ["280300207", "funda", "estuche", "case", "protector", "laser", "láser", "vfl"],
    },
    "lapiz_limpiador_conector_fo": {
        "label": "Lápiz limpiador conector FO",
        "keywords": ["280300202", "lapiz", "lápiz", "limpiador", "cleaner pen", "one-click", "conector", "fo", "fibra"],
    },
    "limpieza": {
        "label": "Kit de limpieza",
        "keywords": ["limpieza", "alcohol", "isoprop", "cletop", "cleaner", "toall", "pano", "paño"],
    },
    "baterias": {
        "label": "Baterías o cargadores",
        "keywords": ["bateria", "batería", "baterias", "baterías", "cargador", "charger", "usb"],
    },
    "cartuchera_herramientas": {
        "label": "Cartuchera porta herramientas",
        "keywords": ["cartuchera", "porta herramientas", "porta-herramientas", "cinturon", "cinturón"],
    },
    "cartuchera_destornilladores_mini": {
        "label": "Cartuchera destornilladores mini",
        "keywords": ["cartuchera", "destornillador", "destornilladores", "mini", "precision", "precisión"],
    },
}
