CHECKLIST_SECTIONS = [
    {
        "key": "seguridad",
        "title": "Elementos de Seguridad (EPP y Entorno)",
        "weight": 30,
        "items": [
            {"key": "casco", "label": "Uso de casco de seguridad", "critical": True},
            {"key": "lentes", "label": "Uso de lentes de proteccion", "critical": False},
            {"key": "chaleco", "label": "Uso de chaleco reflectante", "critical": True},
            {"key": "botas", "label": "Uso de botas de seguridad", "critical": True},
            {"key": "senalizacion", "label": "Señalizacion del area de trabajo", "critical": True},
            {
                "key": "guantes_fibra_sintetica_poliuretano",
                "label": "Guantes de fibra sintética con palma y dedos de poliuretano",
                "critical": True,
            },
            {
                "key": "guante_dielectrico_1000v",
                "label": "Guante dieléctrico (tensión de uso 1000 V, tensión de prueba máximo 5000 V)",
                "critical": True,
            },
            {"key": "orden_entorno", "label": "Orden y limpieza del entorno", "critical": False},
            {"key": "detector_voltaje", "label": "280300104 - Detector de voltaje", "critical": True},
            {
                "key": "mentonera_libus_15mm_gancho_c",
                "label": "730100004 - Mentonera Libus 15mm c/logo (Gancho C)",
                "critical": True,
            },
            {"key": "cinta_peligro", "label": "Cinta de peligro", "critical": True},
            {"key": "conector_cinta_0_8m", "label": "67932 - CONECTOR CINTA 0.8M", "critical": True},
            {"key": "conos", "label": "Conos", "critical": True},
            {"key": "arnes_completo_anticaidas", "label": "Arnés completo anticaídas", "critical": True},
            {"key": "cola_amarre_separada", "label": "Cola de amarre separada", "critical": True},
            {"key": "extintor", "label": "Extintor", "critical": True},
            {"key": "botiquin", "label": "Botiquín de primeros auxilios", "critical": True},
        ],
    },
    {
        "key": "herramientas",
        "title": "Estado de Herramientas (Kit de Fibra Optica)",
        "weight": 15,
        "items": [
            {"key": "fusionadora", "label": "Fusionadora operativa", "critical": False},
            {"key": "cortadora", "label": "Cortadora de FO (Cleaver)", "critical": True},
            {"key": "estuche_cleaver", "label": "Estuche de Cleaver", "critical": False},
            {"key": "pinza_crimpar_rj5_11_9", "label": "PINZ.P/ CRIMPAR. CONEC. TEL RJ5.11.9 cod 390100106", "critical": False},
            {"key": "tijera_cortadora_fo", "label": "TIJERA CORTADORA FO cod 280300201", "critical": False},
            {"key": "pinza_peladora_claus_cfs2", "label": "280300208 - Pinza peladora Claus CFS2", "critical": False},
            {"key": "peladora_drop_plano", "label": "Peladora de Drop plano", "critical": False},
            {"key": "medidor", "label": "Power Meter", "critical": True},
            {"key": "laser_localizador_fallas", "label": "Laser localizador de fallas FO", "critical": False},
            {
                "key": "funda_laser_localizador_fallas",
                "label": "Funda para laser localizador de fallas FO",
                "critical": False,
            },
            {"key": "lapiz_limpiador_conector_fo", "label": "Lápiz limpiador conector FO", "critical": False},
            {"key": "limpieza", "label": "Alcohol Isopropilico + Paño", "critical": False},
            {"key": "orden_kit", "label": "Bolso kit de fibra", "critical": False},
        ],
    },
    {
        "key": "herramientas_mano",
        "title": "Herramientas de mano",
        "weight": 10,
        "items": [
            {
                "key": "mano_alicate_chico_aislado",
                "label": "280300103 - Alicate chico aislado a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300103",
                "evidence_required": True,
            },
            {
                "key": "mano_destornillador_ph_aislado",
                "label": "281300012 - Destornillador PH aislado Ø6x100mm",
                "critical": False,
                "hand_tool": True,
                "material_code": "281300012",
                "evidence_required": True,
            },
            {
                "key": "mano_destornillador_pl_aislado",
                "label": "281300013 - Destornillador PL aislado Ø6.5x150mm",
                "critical": False,
                "hand_tool": True,
                "material_code": "281300013",
                "evidence_required": True,
            },
            {
                "key": "mano_martillo_bolita_500",
                "label": "280700022 - Martillo de 500 grs bolita",
                "critical": False,
                "hand_tool": True,
                "material_code": "280700022",
                "evidence_required": True,
            },
            {
                "key": "mano_pinza_punta_aislada",
                "label": "280300101 - Pinza de punta aislada a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300101",
                "evidence_required": True,
            },
            {
                "key": "mano_pinza_universal_aislada",
                "label": "280300100 - Pinza universal aislada a 1000V",
                "critical": False,
                "hand_tool": True,
                "material_code": "280300100",
                "evidence_required": True,
            },
            {
                "key": "taladro_rotopercutor_electroneumatico",
                "label": "280100006 - Taladro rotopercutor electroneumático",
                "critical": False,
                "hand_tool": True,
                "material_code": "280100006",
                "evidence_required": True,
            },
            {
                "key": "mecha_encastre_8x110_widia",
                "label": "280600137 - Mecha de encastre 8x110mm widia",
                "critical": False,
                "hand_tool": True,
                "material_code": "280600137",
                "evidence_required": True,
            },
            {
                "key": "mecha_encastre_12x450_widia",
                "label": "280600181 - Mecha de encastre 12x450mm widia",
                "critical": False,
                "hand_tool": True,
                "material_code": "280600181",
                "evidence_required": True,
            },
            {
                "key": "mecha_encastre_6x110_widia",
                "label": "280600194 - Mecha de encastre 6x110mm widia",
                "critical": False,
                "hand_tool": True,
                "material_code": "280600194",
                "evidence_required": True,
            },
            {
                "key": "Bolso_herramientas",
                "label": "Bolso de herramientas",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": True,
            },
            {
                "key": "cartuchera_destornilladores_mini",
                "label": "Cartuchera para destornilladores mini",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": True,
            },
            {
                "key": "mano_alarge",
                "label": "Alarge",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": True,
            },
            {
                "key": "mano_cinta_pasacable",
                "label": "Cinta Pasacable",
                "critical": False,
                "hand_tool": True,
                "material_code": "",
                "evidence_required": True,
            },

        ],
    },
    {
        "key": "vehiculo",
        "title": "Estado del Vehículo",
        "weight": 20,
        "items": [
            {"key": "documentacion", "label": "Cédula de Identificación del Automotor", "critical": True},
            {"key": "seguro_vehicular", "label": "Seguro vehicular", "critical": True},
            {"key": "oblea_gnc", "label": "Oblea de GNC", "critical": True},
            {"key": "rto", "label": "RTO", "critical": True},
            {"key": "neumaticos", "label": "Neumáticos", "critical": True},
            {"key": "luces", "label": "Luces operativas", "critical": True},
            {"key": "elementos_emergencia", "label": "Kit Elementos de Emergencia", "critical": True},
            {"key": "rueda_auxilio", "label": "Rueda de auxilio", "critical": True},
            {"key": "gato_hidraulico", "label": "Gato hidráulico", "critical": True},
            {"key": "llave_fuerza", "label": "Llave de fuerza", "critical": True},
            {"key": "orden_limpieza_habitaculo", "label": "Orden y limpieza de Habitáculo", "critical": False},
            {"key": "orden_limpieza_zona_carga", "label": "Orden y limpieza de Zona de carga", "critical": False},
            {"key": "carga_segura", "label": "Escalera Plegable/ telescopica", "critical": False},
            {"key": "porta_escalera", "label": "Porta escalera", "critical": False},
            {
                "key": "escalera_aluminio_extensible",
                "label": "Escalera de aluminio extensible (11/13 peldaños)",
                "critical": True,
            },
            {
                "key": "escalera_fibra_tijera_doble",
                "label": "Escalera de fibra de vidrio tipo tijera doble",
                "critical": True,
            },
            {
                "key": "edv",
                "label": "+EDV (Estado del vehículo)",
                "critical": False,
                "optional": True,
                "evidence_required": False,
                "multi_photo": True,
            },
        ],
    },
    {
        "key": "calidad_instalaciones",
        "title": "Control de Calidad de Instalaciones",
        "weight": 15,
        "items": [
            {"key": "nomenclado", "label": "Nomenclado", "critical": False},
            {"key": "rabillado", "label": "Rabillado", "critical": False},
            {"key": "tensado", "label": "Tensado", "critical": False},
            {"key": "reten_a_cadena", "label": "Reten a cadena", "critical": False},
            {"key": "piton_8_retencion", "label": "Pitón del 8 (retención)", "critical": False},
            {"key": "recorrido_fibra_piton_6", "label": "Recorrido de fibra con pitón del 6", "critical": False},
            {
                "key": "recorrido_fibra_presintada_otro_servicio",
                "label": "Recorrido de fibra presintada a otro Servicio",
                "critical": False,
            },
            {"key": "ingreso_caneria", "label": "Ingreso por cañeria", "critical": False},
            {"key": "ingreso_nueva_perforacion", "label": "Ingreso por nueva perforacion", "critical": False},
            {
                "key": "ingreso_perforacion_existente",
                "label": "Ingreso por perforacion existente",
                "critical": False,
            },
            {"key": "tubo_pasapared", "label": "Tubo pasapared", "critical": False},
            {"key": "loop", "label": "Loop", "critical": False},
            {"key": "sellador", "label": "Sellador", "critical": False},
            {"key": "engrampado_por_vertice", "label": "Engrampado por vertice", "critical": False},
            {"key": "sticker_autoadhesivo", "label": "Sticker autoadhesivo", "critical": False},
        ],
    },
]

QC_SECTION_KEY = "calidad_instalaciones"

AUDIT_CHECKLIST_SECTIONS = [
    section for section in CHECKLIST_SECTIONS if section.get("key") != QC_SECTION_KEY
]


TOOL_MATCH_RULES = {
    "fusionadora": {
        "label": "Fusionadora",
        "keywords": ["fusionadora", "sumitomo", "fitel", "fsm"],
    },
    "cortadora": {
        "label": "Cortadora de FO (Cleaver)",
        "keywords": ["cortadora", "cleaver", "ct-30", "fc-6", "precision", "precisión"],
    },
    "pinza_peladora_claus_cfs2": {
        "label": "Pinza peladora Claus CFS2",
        "keywords": ["280300208", "pinza peladora", "claus", "cfs2"],
    },
    "peladora_drop_plano": {
        "label": "Peladora de Drop plano",
        "keywords": ["280300209", "peladora", "drop", "plano", "flat drop", "peladora drop", "drop plano"],
    },
    "medidor": {
        "label": "Medidor de potencia",
        "keywords": ["medidor", "power meter", "powermeter", "medidor de potencia", "otdr"],
    },
    "laser_localizador_fallas": {
        "label": "Laser localizador de fallas FO",
        "keywords": ["laser", "láser", "localizador", "falla", "fallas", "vfl", "visual fault locator"],
    },
    "funda_laser_localizador_fallas": {
        "label": "Funda para laser localizador de fallas FO",
        "keywords": ["280300207", "funda", "estuche", "case", "protector", "laser", "láser", "vfl"],
    },
    "lapiz_limpiador_conector_fo": {
        "label": "Lápiz limpiador conector FO",
        "keywords": ["280300202", "lapiz", "lápiz", "limpiador", "cleaner pen", "one-click", "conector", "fo", "fibra"],
    },
    "limpieza": {
        "label": "Kit de limpieza",
        "keywords": ["limpieza", "alcohol", "isoprop", "cletop", "cleaner", "toall", "pano", "paño"],
    },
    "cartuchera_herramientas": {
        "label": "Cartuchera porta herramientas",
        "keywords": ["cartuchera", "porta herramientas", "porta-herramientas", "cinturon", "cinturón"],
    },
    "cartuchera_destornilladores_mini": {
        "label": "Cartuchera destornilladores mini",
        "keywords": ["cartuchera", "destornillador", "destornilladores", "mini", "precision", "precisión"],
    },
    "taladro_rotopercutor_electroneumatico": {
        "label": "Taladro rotopercutor electroneumático",
        "keywords": ["280100006", "taladro", "rotopercutor", "electroneumatico", "electroneumático"],
    },
    "mecha_encastre_8x110_widia": {
        "label": "Mecha encastre 8x110mm widia",
        "keywords": ["280600137", "mecha", "encastre", "8x110", "8x110mm", "8 x 110", "widia"],
    },
    "mecha_encastre_12x450_widia": {
        "label": "Mecha encastre 12x450mm widia",
        "keywords": ["280600181", "mecha", "encastre", "12x450", "12x450mm", "12 x 450", "widia"],
    },
    "mecha_encastre_6x110_widia": {
        "label": "Mecha encastre 6x110mm widia",
        "keywords": ["280600194", "mecha", "encastre", "6x110", "6x110mm", "6 x 110", "widia"],
    },
    "pinza_crimpar_rj5_11_9": {
        "label": "PINZ.P/ CRIMPAR. CONEC. TEL RJ5.11.9",
        "keywords": ["390100106", "pinza", "crimpar", "conector", "tel", "rj5.11.9"],
    },
    "tijera_cortadora_fo": {
        "label": "TIJERA CORTADORA FO",
        "keywords": ["280300201", "tijera", "cortadora", "fo", "fibra optica"],
    },
    "mano_pinza_punta_aislada": {
        "label": "Pinza de punta aislada a 1000V",
        "keywords": ["280300101", "pinza", "punta", "aislada", "1000v"],
    },
    "mano_alicate_chico_aislado": {
        "label": "Alicate chico aislado a 1000V",
        "keywords": ["280300103", "alicate", "chico", "aislado", "1000v"],
    },
}
